# Generated by Django 4.2.7 on 2024-06-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niup', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
