# Generated by Django 4.2.7 on 2024-06-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataukom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alamat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='niup',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
