# Generated by Django 4.2.7 on 2024-06-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataukom', '0002_alter_person_alamat_alter_person_niup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='niup',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
