# Generated by Django 4.2.7 on 2024-06-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataukom', '0003_remove_person_id_alter_person_niup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('niup', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
